### ISSUE TITLE
background-color property in .my-theme is being overruled by .boring

### ISSUE THREAD

**Issue by cyberius0** [pachanka/Ptty#10]
Hello,

I want to change the background color of the terminal.
So I did what your documentation says:
- added the CSS theme ".my-theme { .... }" to 	<style> </style> in the head section of the document
- changed background-color property to my color
- added var $ptty = $('#terminal').Ptty({ theme : 'my-theme' ...

What happens now:
The background color doesn't change.
But, I can change the font size with .my-theme (!!) so .my-theme is beeing used somehow.

I looked it up with Firefox element inspector and it seems the background-color property is being overruled / overwritten by ".boring .content" from ptty.jquery.js

My solution:

Delete line number 164 in ptty.query.js:
'.boring, .boring .prompt, .boring .content' '{ font-family: "Courier New", Courier, monospace; background-color: #111; color: #ddd; }')

Then I can set the background color via .my-theme.

Why is the property overruled by .boring?

**Comment by pachanka** [comment]
Hey @cyberius0 ,

I think whats happening is that you are defining the css, but maybe not telling ptty to use it?

[Here is a demo that shows how to load themes in Ptty](https://goto.pachanka.org/ptty/examples/theme-usage).

Because Ptty comes with the "boring" theme by default, if you want to use a different theme you will need to define it ether when starting ptty:

```js
// Start Ptty with the ".pony" css class.
var $ptty = $('#terminal').Ptty({ theme : 'pony' });
```

Or by using the `$ptty.change_settings` method at some point.

```js
$ptty.change_settings({ 'theme' : 'pony' });
```

It's a good idea to grab the [template theme](https://goto.pachanka.org/ptty/docs/#theme) from the docs and start from there. Or if you decide you don't like any of the CSS involved you can always use the [native_css](https://goto.pachanka.org/ptty/docs/#settings) option (setting it to _false_) and start from scratch with a copy of the [default css](https://goto.pachanka.org/ptty/docs/#default-css).

Let me know how it goes.

\- Pachanka
