### ISSUE TITLE
How about remote rpc like jquery.terminal?

### ISSUE THREAD

**Issue by denghongcai** [pachanka/Ptty#4]
https://github.com/jcubic/jquery.terminal

This project can pass command to rpc service and get backend support. Your project is mini and I like the way you design it. Could u add this feature?

**Comment by pachanka** [comment]
Hi,
Part of what I like about Ptty is that its simple, so instead of adding RPC support you can chain it to the awesome [jquery-jsonrpc](https://github.com/datagraph/jquery-jsonrpc) library and it will still be about a third of the weight of jquery.terminal.

Here is an (untested) example:
<pre><code>$.register_command(
    'rpc', 
    'Uses JSON-RPC to talk to a server.', 
    'rpc', 
    function(args){
        $.jsonRPC.request('method.name', {
          params: args.split(/\s+/), // Split at white spaces
          success: function(result) {
            // Do something with the result here
            // It comes back as an RPC 2.0 compatible response object
          },
          error: function(result) {
            // Result is an RPC 2.0 compatible response object
          }
        });
        return {
            type : 'print',
            out      : cmd_date(args);
        }
    }
);
</code></pre>

Let me know if that works for you.

**Comment by pachanka** [comment]
Closed due to inactivity.
